### ISSUE TITLE
为什么最新16.2解压后是16.1呢

### ISSUE THREAD

**Issue by zengmaolin-rfl** [jijiucheng/JJC_iOS_DeviceSupport#2]
为什么最新16.2解压后是16.1呢

**Comment by jijiucheng** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by jijiucheng** [comment]
> 为什么最新16.2解压后是16.1呢

当下根据官方在 `2022.12.13` 号发布的 `Xcode_14.2（14C18）` 正式版本中，并没有提供 `iOS16.2` 的支持文件，所以只需要将 
 `16.2(Xcode_14.2(14C18)).zip` 中解压的 `16.1` 文件名更改为 `16.2` 放入对应的目录文件夹中即可。
