### ISSUE TITLE
请问哪里可以找到watch os最新的支持文件那

### ISSUE THREAD

**Issue by crosstmh** [jijiucheng/JJC_iOS_DeviceSupport#3]
感谢

**Comment by jijiucheng** [comment]
当下所有的 `DeviceSupport` 文件都是从 [苹果官方的开发者网站：https://developer.apple.com/download/](https://developer.apple.com/download/) 下载的

**Comment by jijiucheng** [comment]
[WatchOS_v9.4（Xcode_v14.3.1(14E300c)）.zip](https://github.com/jijiucheng/JJC_iOS_DeviceSupport/files/11637379/WatchOS_v9.4.Xcode_v14.3.1.14E300c.zip)

这个是我从官网下载的 `WatchOS_v9.4` 是最新的 `WatchOS` 支持文件，是从 `Xcode_v14.3.1` 中提取的。

**Comment by crosstmh** [comment]
哎，我的macbook太老了，不让更新系统了，所以没法更新xcode到14，但是要开发调试watchos 9.5的应用，苦恼

**Comment by jijiucheng** [comment]
> 哎，我的macbook太老了，不让更新系统了，所以没法更新xcode到14，但是要开发调试watchos 9.5的应用，苦恼

上面的 [WatchOS_v9.4（Xcode_v14.3.1(14E300c)）.zip](https://github.com/jijiucheng/JJC_iOS_DeviceSupport/files/11637379/WatchOS_v9.4.Xcode_v14.3.1.14E300c.zip) 是我从官网上最新的 `Xcode_v14.3.1` 上提取出来的，且并没有对应的 `9.5` 和 `9.6` 两个版本的支持文件，而最新的 `WatchOS` 版本已经到 `WatchOS_v9.6_beta2` 了，所以你当下如果想调试对应的版本的话，可以手动将上面的 `WatchOS_v9.4` 解压后，直接更名为 `9.5` 或 `9.6` 就可以调试。

**Comment by crosstmh** [comment]
试过命名为9.5了，还是提示有问题，不像ios16.5，直接把16.4改名为16.5也可以~，我再找找，感谢帮助

**Comment by jijiucheng** [comment]
> 试过命名为9.5了，还是提示有问题，不像ios16.5，直接把16.4改名为16.5也可以~，我再找找，感谢帮助

客气
