### ISSUE TITLE
能不能更新一下watchos的支持文件那

### ISSUE THREAD

**Issue by crosstmh** [jijiucheng/JJC_iOS_DeviceSupport#4]
我的笔记本太老了，xcode和系统都不让更新了，开发watchos9.5的app没法真机调试，一直在找这个文件，感谢那

**Comment by jijiucheng** [comment]
> 我的笔记本太老了，xcode和系统都不让更新了，开发watchos9.5的app没法真机调试，一直在找这个文件，感谢那

[WatchOS_v9.5(Xcode_15_beta(15A5160n)).zip](https://github.com/jijiucheng/JJC_iOS_DeviceSupport/files/11684125/WatchOS_v9.5.Xcode_15_beta.15A5160n.zip)

**Comment by crosstmh** [comment]
非常感谢~~
