### ISSUE TITLE
17.4真机包文件呢？ovO?

### ISSUE THREAD

**Issue by GoldFishLi** [jijiucheng/JJC_iOS_DeviceSupport#5]

**Comment by jijiucheng** [comment]
README 文件里已经声明了：

2023.11.15 更新：
经测试发现，Xcode 14.x 的版本实际上应该无法运行 iOS 17.x 系列的版本，必须升级到 Xcode 15.x 才可以，且 macOS 系统需要升级为 macOS Sonoma 才可以运行 Xcode 15.x；
另外一点就是，一旦升级到了 macOS Sonoma 版本的系统后，Xcode 14.x 将无法运行，不再像以前一样可以运行低版本的 Xcode 版本，请谨慎升级。
